/* PARK SCOPE — AGPL-3.0. Images stay on the user's device. */
'use strict';
const $=id=>document.getElementById(id),G=Geometry;
const S={examples:[],current:null,image:null,boxes:[],roi:[],excluded:new Set(),engine:null,busy:false,loading:false,editing:false,points:[],selected:null,scale:1,fitScale:1,ox:0,oy:0,worker:null,elapsedMs:0,history:[],previousRoi:null};
const KEY='parkscope.history.v1';let toastTimer,loadId=0,frame,runTimer;const ctx=$('map').getContext('2d');
const fmt=n=>new Intl.NumberFormat('ja-JP').format(n),day=s=>s?String(s).slice(0,10).replaceAll('-','/'):'不明';
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4800);}
function status(text,detail='',error=false){$('statusText').textContent=text;$('statusText').classList.toggle('error',error);$('runDetail').textContent=detail;}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function switchTab(name){for(const p of document.querySelectorAll('.tab-panel'))p.hidden=p.id!==name;for(const b of document.querySelectorAll('[data-tab]')){const on=b.dataset.tab===name;b.classList.toggle('active',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}if(name==='history')renderHistory();if(name==='analyse')requestAnimationFrame(resize);}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>switchTab(b.dataset.tab);
function setControls(){const locked=S.busy||S.loading;for(const id of ['siteSelect','uploadBtn','roiBtn','captureDate','inheritRoi'])$(id).disabled=locked;for(const id of ['roiBtn','runBtn','focusBtn'])$(id).disabled=locked||!S.image||S.editing;$('runBtn').hidden=S.busy;$('cancelBtn').hidden=!S.busy;$('progress').hidden=!S.busy;$('saveBtn').disabled=locked||S.editing||!S.engine;}
function inArea(b){return S.roi.length>=3&&G.inside([b.cx/S.image.width,b.cy/S.image.height],S.roi);}
function stats(){const threshold=Number($('confidence').value)/100,visible=S.boxes.filter(b=>b.score>=threshold),inside=visible.filter(b=>inArea(b)&&!S.excluded.has(b.id));return {visible,inside,count:inside.length,small:inside.filter(b=>b.classId===10).length,large:inside.filter(b=>b.classId===9).length,outside:visible.filter(b=>!inArea(b)).length};}
function updateResults(){if(!S.image)return;const a=stats();for(const [id,key] of [['count','count'],['smallCount','small'],['largeCount','large'],['outsideCount','outside']])$(id).textContent=S.engine?fmt(a[key]):'—';$('engineBadge').textContent=S.engine==='browser'?'この端末で解析済み':S.engine==='preview'?'YOLO事前解析':'未解析';$('engineBadge').classList.toggle('local',S.engine==='browser');$('resultNote').textContent=S.engine==='browser'?`${(S.elapsedMs/1000).toFixed(1)}秒で解析 / 除外 ${S.excluded.size}件`:S.engine==='preview'?'事前解析の結果です。下のボタンで再解析できます。':'下のボタンで画像を解析します';$('confidenceValue').textContent=$('confidence').value+'%';setControls();drawSoon();}
async function loadImage(record,source){const id=++loadId;S.loading=true;setControls();$('viewerEmpty').hidden=false;$('viewerEmpty').querySelector('p').textContent='画像を読み込んでいます';status('画像を読み込んでいます');try{const image=new Image();image.src=source||record.image;await image.decode();if(id!==loadId)return;S.current={...record};S.image=image;S.boxes=(record.preview?.detections||[]).map((b,i)=>({...b,id:'p'+i}));S.engine=record.preview?'preview':null;S.roi=record.roi.map(p=>p.slice());S.excluded.clear();S.selected=null;S.editing=false;$('boxInfo').hidden=true;$('roiEditor').hidden=true;$('viewer').classList.remove('editing');$('viewerEmpty').hidden=true;$('imageTitle').textContent=record.name;$('district').textContent=record.district||'読み込んだ画像';$('imageKind').textContent=record.upload?'入力画像':'航空写真';$('sourceDate').textContent=day(record.acquiredAt);$('retrieveDate').textContent=record.retrievedAt?day(record.retrievedAt):'—';$('coordinates').textContent=record.latitude?`${record.latitude.toFixed(4)}, ${record.longitude.toFixed(4)}`:'位置情報なし';$('uploadFields').hidden=!record.upload;$('captureDate').value=record.acquiredAt||'';document.querySelector('.compass').hidden=!!record.upload;if(record.upload){$('attribution').textContent='入力画像・解析は端末内';$('attribution').removeAttribute('href');}else{$('attribution').textContent='出典：国土地理院（画像を加工）';$('attribution').href=record.sourceUrl;}resize();fit();status(record.preview?'画像を選んだら、そのまま検出できます':'画像の準備ができました','初回はモデルと推論エンジンを読み込みます');}catch(e){if(id!==loadId)return;S.image=null;S.engine=null;S.boxes=[];$('viewerEmpty').querySelector('p').textContent='画像を読み込めませんでした。画像を選び直してください。';status('画像の読み込みに失敗しました',e.message,true);}finally{if(id===loadId){S.loading=false;setControls();updateResults();}}}
async function init(){try{const r=await fetch('./assets/examples.json');if(!r.ok)throw Error('画像一覧を取得できません');S.examples=await r.json();$('siteSelect').replaceChildren(...S.examples.map(x=>{const o=el('option',x.name);o.value=x.id;return o;}));await loadImage(S.examples[0]);}catch(e){$('siteSelect').replaceChildren(el('option','サンプル画像を取得できません'));$('viewerEmpty').querySelector('p').textContent='接続を確認してページを開き直すか、自分の画像を選んでください。';status('サンプルの読み込みに失敗しました',e.message,true);$('uploadBtn').disabled=false;}readHistory();renderHistory();}
$('siteSelect').onchange=()=>{const r=S.examples.find(x=>x.id===$('siteSelect').value);if(r)loadImage(r);};$('uploadBtn').onclick=()=>$('upload').click();
$('upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>25*1024*1024){toast('25MB以下のJPEG・PNG・WebP画像を選んでください');e.target.value='';return;}S.loading=true;setControls();status('入力画像を準備しています');let url;try{if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('JPEG・PNG・WebPに対応しています');url=URL.createObjectURL(file);const img=new Image();img.src=url;await img.decode();if(img.width*img.height>64000000)throw Error('画像が大きすぎます。8000×8000ピクセル以下にしてください');const scale=Math.min(1,1536/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const normalized=c.toDataURL('image/jpeg',.96);const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))).map(v=>v.toString(16).padStart(2,'0')).join('');S.previousRoi=S.roi.map(p=>p.slice());const inherit=$('inheritRoi').checked;const record={id:'upload-'+hash,siteId:inherit&&S.current?S.current.siteId:'upload',name:file.name.slice(0,120),district:'ユーザーの画像',upload:true,sha256:hash,width:c.width,height:c.height,acquiredAt:null,source:'ユーザー入力画像',roi:inherit&&S.previousRoi.length>=3?S.previousRoi:[[0,0],[1,0],[1,1],[0,1]]};$('siteSelect').value='';await loadImage(record,normalized);if(scale<1)toast('端末の負担を抑えるため長辺1536pxに縮小しました');}catch(error){toast(error.message);status('画像を読み込めませんでした',error.message,true);}finally{if(url)URL.revokeObjectURL(url);e.target.value='';S.loading=false;setControls();}};
$('captureDate').onchange=()=>{if(S.current?.upload){S.current.acquiredAt=$('captureDate').value||null;$('sourceDate').textContent=day(S.current.acquiredAt);}};
$('inheritRoi').onchange=()=>{if(!S.current?.upload)return;S.roi=$('inheritRoi').checked&&S.previousRoi?.length>=3?S.previousRoi.map(p=>p.slice()):[[0,0],[1,0],[1,1],[0,1]];updateResults();toast('異なる構図の場合は、範囲を改めて指定してください');};
$('thresholdHelp').onclick=()=>toast('検出スコアの下限です。正解率ではありません。低くすると見逃しが減る一方、誤検出が増えます。');$('confidence').oninput=updateResults;$('showBoxes').onchange=drawSoon;$('showArea').onchange=drawSoon;
function resize(){const r=$('viewer').getBoundingClientRect();if(r.width<1)return;const d=Math.min(devicePixelRatio||1,2);$('map').width=Math.round(r.width*d);$('map').height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);if(S.image){const old=S.fitScale;S.fitScale=Math.min(r.width/S.image.width,r.height/S.image.height);if(Math.abs(S.scale-old)<.01)fit();}drawSoon();}new ResizeObserver(resize).observe($('viewer'));
function fit(){if(!S.image)return;const r=$('viewer').getBoundingClientRect();S.fitScale=Math.min(r.width/S.image.width,r.height/S.image.height);S.scale=S.fitScale;S.ox=(r.width-S.image.width*S.scale)/2;S.oy=(r.height-S.image.height*S.scale)/2;drawSoon();}
function zoom(f,x,y){if(!S.image)return;const r=$('viewer').getBoundingClientRect();x??=r.width/2;y??=r.height/2;const before=S.scale;S.scale=Math.max(S.fitScale*.8,Math.min(S.fitScale*12,S.scale*f));S.ox=x-(x-S.ox)*S.scale/before;S.oy=y-(y-S.oy)*S.scale/before;drawSoon();}
$('zoomIn').onclick=()=>zoom(1.5);$('zoomOut').onclick=()=>zoom(1/1.5);$('fitBtn').onclick=fit;$('focusBtn').onclick=()=>{if(!S.image||!S.roi.length)return;const r=$('viewer').getBoundingClientRect(),xs=S.roi.map(p=>p[0]*S.image.width),ys=S.roi.map(p=>p[1]*S.image.height),minx=Math.min(...xs),maxx=Math.max(...xs),miny=Math.min(...ys),maxy=Math.max(...ys);S.scale=Math.min(r.width/Math.max(50,maxx-minx),r.height/Math.max(50,maxy-miny))*.82;S.ox=r.width/2-(minx+maxx)/2*S.scale;S.oy=r.height/2-(miny+maxy)/2*S.scale;drawSoon();};
function path(points,close=true){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));if(close)ctx.closePath();}function drawSoon(){cancelAnimationFrame(frame);frame=requestAnimationFrame(draw);}
function draw(){const r=$('viewer').getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);if(!S.image)return;ctx.save();ctx.translate(S.ox,S.oy);ctx.scale(S.scale,S.scale);ctx.drawImage(S.image,0,0);const roi=(S.editing?S.points:S.roi).map(p=>[p[0]*S.image.width,p[1]*S.image.height]);if($('showArea').checked||S.editing){if(roi.length>=3){ctx.beginPath();ctx.rect(0,0,S.image.width,S.image.height);ctx.moveTo(...roi[0]);for(const p of roi.slice(1))ctx.lineTo(...p);ctx.closePath();ctx.fillStyle='rgba(7,14,11,.39)';ctx.fill('evenodd');}if(roi.length){path(roi,!S.editing);ctx.strokeStyle='#ffc475';ctx.lineWidth=2/S.scale;ctx.setLineDash(S.editing?[7/S.scale,5/S.scale]:[]);ctx.stroke();ctx.setLineDash([]);}if(S.editing)for(let i=0;i<roi.length;i++){ctx.beginPath();ctx.arc(...roi[i],5/S.scale,0,Math.PI*2);ctx.fillStyle='#ffc475';ctx.fill();}}
if($('showBoxes').checked&&S.engine){for(const b of stats().visible){const isIn=inArea(b),excluded=S.excluded.has(b.id);path(G.corners(b));ctx.strokeStyle=excluded?'#ffafa2':isIn?'#c0f27b':'#cfdbd1';ctx.lineWidth=(S.selected?.id===b.id?3:1.5)/S.scale;ctx.globalAlpha=isIn?1:.4;ctx.setLineDash(excluded?[3/S.scale,3/S.scale]:[]);ctx.stroke();if(S.selected?.id===b.id){ctx.fillStyle='rgba(192,242,123,.25)';ctx.fill();}ctx.globalAlpha=1;ctx.setLineDash([]);}}ctx.restore();$('zoomLabel').textContent=(S.scale/S.fitScale).toFixed(1)+'×';}
const pointers=new Map();let gesture=null,moved=false;function position(e){const r=$('map').getBoundingClientRect();return [e.clientX-r.left,e.clientY-r.top];}
function beginGesture(){const ps=[...pointers.values()];if(ps.length>=2){gesture={kind:'pinch',center:[(ps[0][0]+ps[1][0])/2,(ps[0][1]+ps[1][1])/2],distance:Math.hypot(ps[1][0]-ps[0][0],ps[1][1]-ps[0][1])};moved=true;}else if(ps.length)gesture={kind:'pan',last:ps[0],start:ps[0]};else gesture=null;}
$('map').onpointerdown=e=>{if(!S.image||S.loading)return;$('map').setPointerCapture(e.pointerId);if(!pointers.size)moved=false;pointers.set(e.pointerId,position(e));beginGesture();};
$('map').onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,position(e));const ps=[...pointers.values()];if(ps.length>=2&&gesture?.kind==='pinch'){const center=[(ps[0][0]+ps[1][0])/2,(ps[0][1]+ps[1][1])/2],dist=Math.hypot(ps[1][0]-ps[0][0],ps[1][1]-ps[0][1]);if(gesture.distance>0)zoom(dist/gesture.distance,...gesture.center);S.ox+=center[0]-gesture.center[0];S.oy+=center[1]-gesture.center[1];gesture.center=center;gesture.distance=dist;drawSoon();}else if(gesture?.kind==='pan'){const p=ps[0];if(Math.hypot(p[0]-gesture.start[0],p[1]-gesture.start[1])>5)moved=true;if(moved){S.ox+=p[0]-gesture.last[0];S.oy+=p[1]-gesture.last[1];drawSoon();}gesture.last=p;}};
$('map').onpointerup=e=>{const p=position(e);if(!moved&&pointers.size===1)tap(p);pointers.delete(e.pointerId);beginGesture();};$('map').onpointercancel=e=>{pointers.delete(e.pointerId);moved=true;beginGesture();};$('map').addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(-e.deltaY*.0015),...position(e));},{passive:false});
function tap(p){const x=(p[0]-S.ox)/S.scale,y=(p[1]-S.oy)/S.scale;if(S.editing){if(x<0||y<0||x>S.image.width||y>S.image.height)return;if(S.points.length>=30)return toast('範囲の頂点は30点までです');S.points.push([x/S.image.width,y/S.image.height]);editUpdate();return;}if(!$('showBoxes').checked)return;const hit=stats().visible.filter(b=>G.inside([x,y],G.corners(b))||Math.hypot(b.cx-x,b.cy-y)<8/S.scale).sort((a,b)=>Math.hypot(a.cx-x,a.cy-y)-Math.hypot(b.cx-x,b.cy-y))[0];S.selected=hit||null;$('boxInfo').hidden=!hit;if(hit){$('boxLabel').textContent=(hit.classId===10?'小型車両':'大型車両')+(inArea(hit)?'':'・範囲外');$('boxScore').textContent=`検出スコア ${Math.round(hit.score*100)}%`;$('excludeBox').textContent=S.excluded.has(hit.id)?'集計に戻す':'集計から除外';}drawSoon();}
$('closeBox').onclick=()=>{S.selected=null;$('boxInfo').hidden=true;drawSoon();};$('excludeBox').onclick=()=>{const b=S.selected;if(!b)return;if(S.excluded.has(b.id))S.excluded.delete(b.id);else S.excluded.add(b.id);$('excludeBox').textContent=S.excluded.has(b.id)?'集計に戻す':'集計から除外';updateResults();};
function beginEdit(){S.editing=true;S.points=[];$('roiEditor').hidden=false;$('viewer').classList.add('editing');$('boxInfo').hidden=true;setControls();editUpdate();$('viewer').scrollIntoView({block:'center',behavior:'smooth'});}
function editUpdate(){$('applyRoi').disabled=S.points.length<3||G.area(S.points)<.0001;$('undoPoint').disabled=!S.points.length;$('roiHint').textContent=S.points.length?`${S.points.length}点を指定。駐車場を囲んで確定`:'駐車場を囲むように、3点以上タップ';drawSoon();}
function endEdit(apply){if(apply){if(S.points.length<3||G.area(S.points)<.0001)return;for(let i=0;i<S.points.length;i++)for(let j=i+2;j<S.points.length;j++){if(i===0&&j===S.points.length-1)continue;const a=S.points[i],b=S.points[(i+1)%S.points.length],c=S.points[j],d=S.points[(j+1)%S.points.length],cross=(p,q,r)=>(q[0]-p[0])*(r[1]-p[1])-(q[1]-p[1])*(r[0]-p[0]);if(cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0)return toast('線が交差しています。外周に沿って指定し直してください');}S.roi=S.points.map(p=>p.slice());}S.editing=false;S.points=[];$('roiEditor').hidden=true;$('viewer').classList.remove('editing');updateResults();}
$('roiBtn').onclick=beginEdit;$('undoPoint').onclick=()=>{S.points.pop();editUpdate();};$('cancelRoi').onclick=()=>endEdit(false);$('applyRoi').onclick=()=>endEdit(true);$('map').onkeydown=e=>{if(e.key==='Escape'){if(S.editing)endEdit(false);else $('closeBox').click();}if(e.key==='Enter'&&S.editing)endEdit(true);if(e.key==='+'||e.key==='=')zoom(1.3);if(e.key==='-')zoom(1/1.3);};
async function run(){if(!S.image||S.busy||S.editing)return;S.busy=true;setControls();$('progress').value=0;status('YOLOを起動しています','初回はモデル約11MB＋実行エンジンを読み込みます');try{const bitmap=await createImageBitmap(S.image);if(!S.busy){bitmap.close();return;}if(!S.worker)S.worker=new Worker('./yolo-worker.js?v=1');const worker=S.worker;worker.onmessage=({data:d})=>{if(worker!==S.worker||!S.busy)return;if(d.type==='progress'){$('progress').value=d.percent;status(d.message,d.stage==='model'?'初回の準備には少し時間がかかります':'端末内で解析中。写真の撮影日時は変わりません');}else if(d.type==='result'){clearTimeout(runTimer);S.busy=false;S.boxes=d.boxes;S.engine='browser';S.elapsedMs=d.elapsedMs;S.excluded.clear();S.selected=null;$('boxInfo').hidden=true;status('検出が完了しました',`${d.tiles}分割で解析 / 枠をタップして結果を確認`);updateResults();}else if(d.type==='error')fail(d.message);};worker.onerror=e=>fail(e.message||'推論エンジンを起動できませんでした');worker.postMessage({type:'detect',bitmap,tileSize:384},[bitmap]);runTimer=setTimeout(()=>fail('処理が長時間応答しないため中止しました。画像を小さくして再試行してください。'),240000);}catch(e){fail(e.message);}}
function fail(message){clearTimeout(runTimer);S.worker?.terminate();S.worker=null;S.busy=false;status('検出を完了できませんでした',message,true);setControls();toast('再度「YOLOで検出」でやり直せます。SafariやChromeの最新版でもお試しください。');}
$('runBtn').onclick=run;$('cancelBtn').onclick=()=>{clearTimeout(runTimer);S.worker?.terminate();S.worker=null;S.busy=false;setControls();status('解析を中止しました','直前の完了済み結果がある場合は、その結果を表示しています');};
function readHistory(){try{const data=JSON.parse(localStorage.getItem(KEY)||'[]');S.history=Array.isArray(data)?data.filter(x=>x&&typeof x.id==='string'&&Number.isFinite(x.count)&&x.count>=0&&typeof x.name==='string').slice(-100):[];}catch{S.history=[];toast('保存済みの記録を読み込めませんでした');}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(S.history));return true;}catch{toast('ブラウザに保存できませんでした。空き容量やプライベートモードを確認してください。');return false;}}
$('saveBtn').onclick=()=>{if(!S.engine||S.busy)return;const a=stats(),c=S.current,id=c.sha256,prev=S.history.find(x=>x.id===id),entry={id,siteId:c.siteId,name:c.name,source:c.source,captureDate:c.acquiredAt||null,recordedAt:prev?.recordedAt||new Date().toISOString(),updatedAt:new Date().toISOString(),count:a.count,small:a.small,large:a.large,outside:a.outside,threshold:Number($('confidence').value)/100,excluded:S.excluded.size,roi:S.roi,model:'YOLO11n-OBB',engine:S.engine,sha256:c.sha256};const before=S.history.slice();S.history=S.history.filter(x=>x.id!==id);S.history.push(entry);S.history=S.history.slice(-100);if(persist()){toast(prev?'この画像の記録を更新しました':'台数と解析条件をこの端末に保存しました');renderHistory();}else S.history=before;};
function filteredHistory(){const f=$('historyFilter').value;return S.history.filter(x=>f==='all'||x.siteId===f);}
function renderHistory(){const selected=$('historyFilter').value,groups=new Map();for(const r of S.history)if(!groups.has(r.siteId))groups.set(r.siteId,r.siteId==='upload'?'入力画像':S.examples.find(e=>e.siteId===r.siteId)?.name||r.name);const all=el('option','すべての場所');all.value='all';$('historyFilter').replaceChildren(all,...[...groups].map(([id,name])=>{const o=el('option',name);o.value=id;return o;}));if(groups.has(selected))$('historyFilter').value=selected;$('historyBadge').textContent=S.history.length;const rows=filteredHistory();$('historyList').replaceChildren();if(!rows.length){const empty=el('div',undefined,'empty-history');empty.append(el('h2','まだ記録がありません'),el('p','画像を解析して「結果を記録」を押すと、ここに残ります。'));$('historyList').append(empty);}for(const r of [...rows].reverse()){const item=el('article',undefined,'history-item'),text=el('div'),v=el('span',undefined,'history-count');text.append(el('h3',r.name),el('p',`撮影日 ${day(r.captureDate)} / ${r.engine==='browser'?'端末で解析':'YOLO事前解析'}`),el('p',`記録 ${day(r.updatedAt)} · しきい値 ${Math.round(r.threshold*100)}% · 除外 ${r.excluded||0}件`));v.append(document.createTextNode(fmt(r.count)),el('small',' 台'));const del=el('button','×','delete-item');del.setAttribute('aria-label',r.name+'の記録を削除');del.onclick=()=>{if(!confirm('この記録を削除しますか？'))return;S.history=S.history.filter(x=>x.id!==r.id);persist();renderHistory();};item.append(text,v,del);$('historyList').append(item);}drawHistoryChart(rows);$('exportCsv').disabled=!rows.length;$('clearHistory').disabled=!S.history.length;}
$('historyFilter').onchange=renderHistory;
function drawHistoryChart(rows){$('historyChart').replaceChildren();if(!rows.length){$('historyChart').append(el('p','保存した台数の比較グラフ','muted'));return;}const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 700 180');svg.setAttribute('role','img');svg.setAttribute('aria-label',rows.map((r,i)=>`${i+1}番目 ${r.count}台`).join('、'));const add=(tag,attrs,text)=>{const e=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;svg.append(e);return e;};const max=Math.max(10,...rows.map(r=>r.count)),pts=rows.map((r,i)=>[rows.length===1?350:50+i*600/(rows.length-1),140-r.count/max*110]);for(const n of [0,.5,1]){const y=140-n*110;add('line',{x1:45,x2:670,y1:y,y2:y,stroke:'#34443b'});add('text',{x:5,y:y+4,fill:'#a5b4a9','font-size':12},Math.round(max*n));}if(pts.length>1)add('polyline',{points:pts.map(p=>p.join(',')).join(' '),fill:'none',stroke:'#c0f27b','stroke-width':2});pts.forEach(([x,y],i)=>{const c=add('circle',{cx:x,cy:y,r:4,fill:'#c0f27b'});const title=document.createElementNS(ns,'title');title.textContent=`${rows[i].name}: ${rows[i].count}台`;c.append(title);if(rows.length<13){add('text',{x,y:y-10,fill:'#eef3e9','text-anchor':'middle','font-size':13},rows[i].count);add('text',{x,y:166,fill:'#a5b4a9','text-anchor':'middle','font-size':11},String(i+1));}});$('historyChart').append(svg);}
$('clearHistory').onclick=()=>{if(!confirm('このブラウザに保存した全記録を削除しますか？'))return;S.history=[];persist();renderHistory();};
function csvCell(v){let s=v==null?'':String(v);if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
$('exportCsv').onclick=()=>{const fields=['name','siteId','captureDate','updatedAt','count','small','large','outside','threshold','excluded','model','engine','source','sha256','roi'],rows=filteredHistory(),csv='\uFEFF'+fields.join(',')+'\r\n'+rows.map(r=>fields.map(k=>csvCell(k==='roi'?JSON.stringify(r.roi):r[k])).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='parkscope-observations.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};
// Read-only inspection surface for integration tests. No mock inference path.
Object.defineProperty(window,'parkingApp',{value:{snapshot:()=>({ready:!!S.image,engine:S.engine,busy:S.busy,count:S.image?stats().count:null,boxes:S.boxes.map(b=>({...b})),roi:S.roi.map(p=>p.slice()),history:S.history.length,transform:{scale:S.scale,ox:S.ox,oy:S.oy},image:S.image?{width:S.image.width,height:S.image.height}:null})}});init();
