import fs from 'node:fs';
import assert from 'node:assert/strict';
import {decode,inside,similarity} from '../web/detect.mjs';
const buf=fs.readFileSync('dist/raw.bin');const data=new Float32Array(buf.buffer,buf.byteOffset,buf.byteLength/4);
const boxes=decode(data,8400,2.5),meta=JSON.parse(fs.readFileSync('dist/sample.json','utf8'));
const selected=boxes.filter(b=>b.score>=.25&&inside(b.x,b.y,meta.roi));
assert(boxes.length>0,'Real aerial image must yield vehicle detections');
assert(inside(5,5,[[0,0],[10,0],[10,10],[0,10]]));
assert(!inside(15,5,[[0,0],[10,0],[10,10],[0,10]]));
assert(similarity({x:0,y:0,w:10,h:5,angle:0},{x:0,y:0,w:10,h:5,angle:0})>.99);
assert.equal(decode(new Float32Array(20*8400)).length,0);
fs.writeFileSync('dist/verification.json',JSON.stringify({model:meta.model,vehiclesAt25:selected.length,totalCandidates:boxes.length,boxes:selected},null,2));
fs.unlinkSync('dist/raw.bin');
console.log('VERIFIED_REAL_IMAGE',selected.length,'vehicles in ROI;',boxes.length,'candidates');
